import Logo from '@/components/logo';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from './area/header';
import Footer from './area/footer';
import { Providers } from '@/app/providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'home',
  description: 'Generated by create next app',
};

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <Header></Header>
        <Logo />
        <Providers>{props.children}</Providers>
        <Footer></Footer>
      </body>
    </html>
  );
}
